site_name: speedrun.js
repo_url: https://github.com/GreepTheSheep/speedrun.js/
repo_name: GreepTheSheep/speedrun.js
copyright: Docs by Greep
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GreepTheSheep
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GreepTheSheep    
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/_fitzherbert_eugene
theme:
  name: null
  custom_dir: docs/mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  icon:
    logo: logo
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: green
    accent: teal
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - search.suggest
    - search.highlight
  plugins:
    - search